### ISSUE TITLE
Failure on MacOS since cp does not support --parents

### ISSUE THREAD

**Issue by ClausHolbechArista** [ansible/tox-ansible#246]
Hi team
tox-ansible fails on MacOS with an error for cp not supporting `--parents`.

This line:
https://github.com/ansible/tox-ansible/blob/d9c7d08dba0d9d01de0ceb38ce17596bb28fe648/src/tox_ansible/plugin.py#L464

contains `--parents` which is not supported on MacOS. ~Changing to `-p` should solve it for all platforms.~ `-p` is not doing the same, so on MacOS ppl would have to install GNU `cp`.

Can you look into other alternatives to make this more portable?

Thanks

**Comment by ssbarnea** [comment]
More portable would be to use a pure python approach and avoid using cp or rsync which both have their own portability issues.
